#!/bin/bash
set -e
. ~/hpcjob/runFunctions.sh

#-------------------------------------
stage[1]="simpleFoam"
stage[2]="pimpleFoam"
stage[3]="pimpleBeamDynFoam"

savefiles[1]=""
savefiles[2]=""
savefiles[3]="BeamDynState_last.dat shape.dat surfaceDisplacementVectors.dat Tip_Disp_IEC.out Mid_Disp_IEC.out position.out load.out"

#dryrun=true
#-------------------------------------

job_init

job_runstage 1

startFrom0=true
job_runstage 2

startFrom0=false
job_runstage 3


