#!/bin/bash
squeue -u $USER |
while read -r line; do
    jobid=`echo $line | awk '{print $1}'`
    if [ "$jobid" == 'JOBID' ]; then continue; fi
    workdir=`scontrol show job $jobid | grep WorkDir`
    workdir=${workdir#*=}
    cd $workdir
    if [ -d 'constant' -a -d 'system' ]; then
        echo ''
        echo "SOWFA jobid=$jobid in $workdir"
        echo '-----'
    elif [ -d 'plt00000' -a -f 'datlog' ]; then
        echo ''
        echo "AMReX jobid=$jobid in $workdir"
        echo '-----'
    elif [ -f 'wrf.exe' ]; then
        echo ''
        echo "WRF jobid=$jobid in $workdir"
        echo '---'
    else
        echo "Unknown simulation $jobid $workdir"
    fi
    t
done
