#!/bin/bash
squeue -u $USER |
while read -r line; do
    jobid=`echo $line | awk '{print $1}'`
    if [ "$jobid" == 'JOBID' ]; then continue; fi
    workdir=`scontrol show job $jobid | grep WorkDir`
    workdir=${workdir#*=}
    cd $workdir
    if [ -d 'constant' -a -d 'system' ]; then
        echo "SOWFA $jobid $workdir"
        t
    elif [ -f 'wrf.exe' ]; then
        echo "WRF $jobid $workdir"
        tail -n 100 rsl.out.0000 | grep '^Timing' | tail -n 1
    else
        echo "Unknown simulation $jobid $workdir"
    fi
done
