#!/bin/bash

#if [ -n "$1" ]; then
#    current=`find $* -name 'RUNNING'`
#else
#    current=`find . -name 'RUNNING'`
#fi
#
#echo "`date`:"
#for f in $current; do
#    d=`dirname $f`
#    (cd $d && echo "$d @ `t`")
#done

i=0
echo "`date`:"
qstat -u equon | while read line; do
    i=$((i+1))
    #echo $i $line
    if [ "$i" -gt 5 ]; then
        id=`echo $line | awk '{print $1}'`
        jobtime=`qstat -f $id | grep 'resources_used.walltime' | awk '{print $NF}'`
        #str=`qstat -f $id | grep 'PBS_O_WORKDIR'`
        str=`qstat -f $id | grep 'PWD'`
        str=${str##*PWD=}
        str=${str%%,*}
        shortpath=${str#/scratch/equon/}
        curtime=`(cd $str && t)`
        #tstr=`echo $curtime | awk '{printf "Time step %d, t= %f\n",$2,$4}'`
        tstr=`echo $curtime | awk '{printf "t= %f s\n",$4}'`
        echo "Job $id ($shortpath) running for $jobtime @ $tstr"
    fi
done

