#!/bin/bash

str=''
n=0
for val in $*; do
    if [ -n "$str" ]; then
        str="$str,$val"
    else
        str="$val"
    fi
    n=$((n+1))
done
str="${str}"

curdir=`getRemotePath`

if [ $n -gt 0 ]; then

    if [[ $1 == $defaultBaseAddr* ]]; then #copy from local to remote

        cmd="scp -r `pwd` $curdir"

    else #copy from remote to local

        if [ $n -gt 1 ]; then
            #echo "scp -r $defaultBaseAddr:$curdir/{$str} ."
            #scp -r $defaultBaseAddr:$curdir/{$str} .
            cmd="scp -r $curdir/{$str} ."
            #cmd="rsync -aPv $curdir/{$str} ."
        else
            #echo "scp -r $defaultBaseAddr:$curdir/$str ."
            #scp -r $defaultBaseAddr:$curdir/$str .
            cmd="scp -r $curdir/$str ."
            #cmd="rsync -aPv $curdir/$str ."
        fi

    fi

    echo $cmd
    eval $cmd
    #eval "$cmd 2>/dev/null"
fi
