#!/bin/bash
# copied from http://unix.stackexchange.com/questions/13464/is-there-a-way-to-find-a-file-in-an-inverse-recursive-search

if [ -z "$1" ]; then
    echo "specify search file"
    exit
fi

slashes=${PWD//[^\/]/}
directory="$PWD"
for (( n=${#slashes}; n>0; --n )); do
    #test -e "$directory/$1" && echo "$directory/$1" && break 
    test -e "$directory/$1" && cd "$directory" && echo "$PWD/$1" && break 
    directory="$directory/.."
done
